"""ajusta coluna id_categoria

Revision ID: 3440b30f427e
Revises: 58bfa1e68b18
Create Date: 2023-08-06 12:04:18.395081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3440b30f427e'
down_revision = '58bfa1e68b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livro')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livro',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=255), nullable=False),
    sa.Column('autor', sa.VARCHAR(length=255), nullable=False),
    sa.Column('ano_publicacao', sa.INTEGER(), nullable=False),
    sa.Column('categoria_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    # ### end Alembic commands ###
